#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Husky pre-commit hook: Running npm install before npm test..."
npm install
echo "Husky pre-commit hook: npm install finished. Running npm test..."
npm test
